main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-tryout/', tryout_create, name='create_tryout'),
    path('edit_tryout/<int:id>/', tryout_edit, name='tryout_edit'),
    path('delete_tryout/<int:id>/', tryout_delete, name='tryout_delete'),
    path('detail_tryout/<int:id>/', tryout_detail, name='tryout_detail'),
    path('add_question/<int:tryout_id>/', question_create, name='question_create'),
    path('edit_question/<int:id>/', question_edit, name='question_edit'),
    path('delete_question/<int:id>/', question_delete, name='question_delete'),
    path("attempt_quiz/<int:tryout_id>/", attempt_quiz, name="attempt_quiz"),
]

quiz_web/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

main/models.py
from django.db import models

# Create your models here.
class Tryout(models.Model) :
    STATUS_CHOICES = [
        (True, "Submitted"),
        (False, "Draft")
    ]
    CATEGORY_CHOICES = [
        ('easy', 'Easy'),
        ('medium', 'Medium'),
        ('hard', 'Hard'),
    ]
    title = models.CharField(max_length=300)
    category = models.CharField(max_length=10, choices=CATEGORY_CHOICES, default='medium')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=False, choices=STATUS_CHOICES)


class Question(models.Model):
    tryout = models.ForeignKey(Tryout, on_delete=models.CASCADE, related_name='questions')
    text = models.TextField()
    answer = models.BooleanField()

main/forms.py
from django import forms
from django.forms import ModelForm
from main.models import Tryout, Question

class TryoutForm(ModelForm):
    class Meta :
        model = Tryout
        fields = ['title', 'category']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'border-4 border-gray-700 p-2 rounded-lg w-full'}),
            'category': forms.Select(attrs={'class': 'border-10 border-gray-700 p-2 rounded-lg w-full'}),
        }

class QuestionForm(ModelForm):
    ANSWER_CHOICES = [
        (True, 'True'),
        (False, 'False'),
    ]

    answer = forms.ChoiceField(
        choices=ANSWER_CHOICES,
        widget=forms.RadioSelect
    )
    class Meta:
        model = Question
        fields = ['text', 'answer']
        widgets = {
            'text': forms.TextInput(attrs={'class': 'border-3 border-gray-700 p-2 rounded-lg w-full'}),
        }

main/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from .models import Tryout, Question
from .forms import TryoutForm, QuestionForm
from .filters import TryoutFilter

#========================================================================
def show_main(req):
    tryouts = Tryout.objects.all()
    myFilter = TryoutFilter(req.GET, queryset=tryouts)
    tryouts = myFilter.qs
    context = {
        'list_tryout': tryouts,
        'filter' : myFilter,
    }
    return render(req, "mainPage/index.html", context)
#========================================================================
def tryout_create(req):
    if req.method == "POST":
        form = TryoutForm(req.POST)
        if form.is_valid():
            form.save()
            return redirect('main:show_main')
    else:
        form = TryoutForm()
    context = {'form': form}
    return render(req, 'addTryout/index.html', context)
#========================================================================
def tryout_edit(req, id):
    tryout = get_object_or_404(Tryout, pk=id)

    if req.method == 'POST':
        form = TryoutForm(req.POST, instance=tryout)
        if form.is_valid():
            form.save()
            return redirect('main:tryout_detail', id)

    else:
        form = TryoutForm(instance=tryout)

    context = {'form': form, 'tryout': tryout}
    return render(req, 'editTryout/index.html', context)
#========================================================================
def tryout_delete(req, id):
    tryout = get_object_or_404(Tryout, pk=id)
    tryout.delete()
    return redirect('main:show_main')
#========================================================================
def tryout_detail(req, id):
    tryout = get_object_or_404(Tryout, pk=id)
    questions = Question.objects.filter(tryout=tryout)
    
    context = {
        'tryout': tryout,
        'questions': questions,
    }
    return render(req, 'detailTryout/index.html', context)
#========================================================================
def question_create(req, tryout_id):
    tryout = get_object_or_404(Tryout, pk=tryout_id)
    
    if req.method == "POST":
        form = QuestionForm(req.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.tryout = tryout
            question.save()
            return redirect('main:tryout_detail', tryout.id)
    else :
        form = QuestionForm()
    
    context = {'form' : form, 'tryout':tryout}
    return render(req, "addQuestion/index.html", context)
#========================================================================
def question_edit(req, id):
    question = get_object_or_404(Question, pk=id)
    tryout = question.tryout
    
    if req.method == "POST":
        form = QuestionForm(req.POST, instance=question)
        if form.is_valid():
            form.save()
            return redirect('main:tryout_detail', id=tryout.id)
    else :
        form = QuestionForm(instance=question)
    context = {'form' : form, 'question':question, 'tryout':tryout}
    return render(req, "editQuestion/index.html", context)
#========================================================================
def question_delete(req, id):
    question = get_object_or_404(Question, pk=id)
    tryout_id = question.tryout.id
    question.delete()
    return redirect('main:tryout_detail', tryout_id)
#========================================================================
def attempt_quiz(req, tryout_id):
    tryout = get_object_or_404(Tryout, pk=tryout_id)
    questions = Question.objects.filter(tryout=tryout)
    
    if req.method == "POST":
        score = 0
        total_questions = questions.count()
        user_answers = {}
        
        for question in questions :
            answer_chosen = req.POST.get(f"question_{question.id}")
            correct_answer = "True" if question.answer else "False"
            
            is_correct = answer_chosen == correct_answer
            
            if is_correct :
                score += 1
            
            user_answers[question.id] = {
                "question" : question.text,
                "user_answer" : answer_chosen,
                "correct_answer" : correct_answer,
                "is_correct" : is_correct,
            }
            
        tryout.status = True
        tryout.save()
        
        return render (req, "quizResult/index.html", {
            "tryout" : tryout,
            "score" : score,
            "total_question" : total_questions,
            "user_answers" : user_answers,
        })
    
    context = {"tryout": tryout, "questions": questions}
    return render(req, "attemptQuiz/index.html", context)

main/templates/addQuestion/index.html
{% extends 'base.html' %}

{% block meta %}
<title>Add Question</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}
<div class="flex flex-col gap-4 mt-5 min-h-screen">
    <div class="container mx-auto px-4 py-4 mt-4 max-w-lg bg-white rounded-lg">
        <h1 class="mt-6 text-center text-4xl font-extrabold text-gray-800 mb-8">Add Question for {{ tryout.title }}</h1>
        <form method="POST" class="space-y-6">
            {% csrf_token %}
            {% for field in form %}
            <div class="flex flex-col">
                <label for="{{ field.id_for_label }}" class="mb-2 font-semibold text-gray-800 text-2xl">
                    {{ field.label }}
                </label>
                <div class="w-full text-2xl rounded-lg">
                    {{ field }}
                </div>
                {% if field.help_text %}
                <p class="mt-1 text-sm text-gray-100">{{ field.help_text }}</p>
                {% endif %}
                {% for error in field.errors %}
                <p class="mt-1 text-sm text-blue-600">{{ error }}</p>
                {% endfor %}
            </div>
            {% endfor %}
            <div class="flex justify-center mt-6 pb-2">
                <button type="submit"
                    class="group relative w-full bg-[#0b79f7] hover:bg-opacity-100 hover:text-white bg-opacity-10 text-[#0b79f7] border border-[#0b79f7] font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out transform flex-row space-x-2 flex items-center justify-center">
                    Add
                </button>
                <a href="{% url 'main:tryout_detail' tryout.id %}"
                    class="group relative w-full bg-red-500 hover:bg-opacity-100 hover:text-white bg-opacity-10 text-[#0b79f7] border border-[#0b79f7] font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out transform flex-row space-x-2 flex items-center justify-center">
                    Cancel
                </a>
            </div>
        </form>
    </div>
    <style>
        textarea {
            width: 100%;
            height: 150px;
            padding: 12px 20px;
            box-sizing: border-box;
            border: 2px solid #ccc;
            border-radius: 4px;
            background-color: #f8f8f8;
            font-size: 16px;
            resize: none;
        }        
    </style>
</div>
{% include 'footer.html' %}
{% endblock %}

main/templates/addTryout/index.html
{% extends 'base.html' %}

{% block meta %}
<title>Add Tryout</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}
<div class="min-h-screen flex flex-col">
    <div class="container mx-auto px-4 py-4 mt-4 max-w-xl bg-white rounded-lg">
        <h1 class="mt-6 text-center text-5xl font-extrabold text-gray-800 mb-8">Add Tryout</h1>
        <form method="POST" class="space-y-6">
            {% csrf_token %}
            {% for field in form %}
            <div class="flex flex-col">
                <label for="{{ field.id_for_label }}" class="mb-2 font-semibold text-gray-800 text-2xl">
                    {{ field.label }}
                </label>
                <div class="w-full text-2xl rounded-xl">
                    {{ field }}
                </div>
            </div>
            {% endfor %}
            <div class="flex justify-center mt-6 pb-2">
                <button type="submit"
                    class="group relative w-full bg-[#0b79f7] hover:bg-opacity-100 hover:text-white bg-opacity-10 text-[#0b79f7] border border-[#0b79f7] font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out transform flex-row space-x-2 flex items-center justify-center">
                    Add
                </button>
                <a href="{% url 'main:show_main' %}"
                    class="group relative w-full bg-red-500 hover:bg-opacity-100 hover:text-white bg-opacity-10 text-[#0b79f7] border border-[#0b79f7] font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out transform flex-row space-x-2 flex items-center justify-center">
                    Cancel
                </a>
            </div>
        </form>
    </div>
</div>
{% include 'footer.html' %}
{% endblock %}

main/templates/attemptQuiz/index.html
{% extends 'base.html' %}

{% block meta %}
<title>Attempt Quiz</title>
{% endblock meta %}

{% block content %}
{% include "navbar.html" %}
<div class="flex flex-col p-5 item-center justify-center gap-4">
    <h2 class="font-medium text-3xl text-center">Attempt Quiz: {{ tryout.title }}</h2>
    
    <form method="POST">
        {% csrf_token %}
        <div class="pt-3 pb-5 space-y-4 min-h-screen">
            {% for question in questions %}
                <div class="flex flex-col p-5 bg-white gap-3 rounded-lg shadow-md">
                    <p class="text-2xl text-gray-800 font-medium" >{{ question.text }}</p>
                    <label class="text-1xl text-gray-800 font-medium">
                        <input type="radio" name="question_{{ question.id }}" value="True" required>
                        True
                    </label>
                    <label class="text-1xl text-gray-800 font-medium">
                        <input type="radio" name="question_{{ question.id }}" value="False" required>
                        False
                    </label>
                </div>
            {% endfor %}
            <a href="{% url 'main:show_main' %}" class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-500 rounded-lg 
            shadow-md transition transform hover:-translate-y-1 hover:scale-10 justify-center" >Back to Main</a>
            <button class="inline-flex bg-green-500 text-white px-4 py-2 rounded-lg shadow-md transition transform
            hover:bg-green-600 hover:-translate-y-1 hover:scale-10" type="submit">Submit</button>
        </div>
    </form>
</div>
{% include "footer.html" %}
{% endblock content %}

main/templates/detailTryout/index.html
{% extends 'base.html' %}

{% block meta %}
<title>{{ tryout.title }}</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}
<body class="w-screen flex flex-col bg-gray-100">
    <div class=" shadow-lg rounded-lg p-6 w-full h-screen">
        <div class="text-center flex flex-col gap-2">
            <h1 class="text-4xl font-bold text-gray-800 mb-2">{{ tryout.title }}</h1>
        </div>

        <h2 class="flex flex-col text-xl font-semibold text-gray-700 mb-3">Questions</h2>
        {% if not tryout.status %}
        <div class="mt-4">
            <a href="{% url 'main:question_create' tryout.id %}" class="inline-flex bg-green-500 text-white px-4 py-2 rounded-lg shadow-md transition transform
            hover:bg-green-600 hover:-translate-y-1 hover:scale-10 my-5">Add Question</a>
        </div>
        {% endif %}
        <div class="space-y-4">
            {% for question in questions %}
                <div class="flex flex-col bg-gray-50 p-4 rounded-lg shadow gap-3">
                    <p class="text-2xl text-gray-800 font-medium">{{ question.text }}</p>
                    <p class="text-gray-600"><strong>Answer:</strong> {% if question.answer %}True{% else %}False{% endif %}</p>
                    {% if not tryout.status %}
                    <div class="mt-2 flex gap-2">
                        <a href="{% url 'main:question_edit' question.id %}" class="text-blue-600 rounded-lg hover:underline">Edit</a>
                        <span class="text-gray-400">|</span>
                        <a href="{% url 'main:question_delete' question.id %}" class="text-red-600 rounded-lg hover:underline">Delete</a>
                    </div>
                    {% endif %}
                </div>
            {% empty %}
                <p class="text-gray-500">No questions available.</p>
            {% endfor %}
        </div>
        
        <div class="mt-6 flex flex-wrap gap-2">
            <a href="{% url 'main:tryout_edit' tryout.id %}" class="inline-flex bg-blue-500 text-white px-4 py-2 rounded-lg shadow-md transition transform
            hover:bg-blue-600 hover:-translate-y-1 hover:scale-10">Edit Tryout</a>
            <a href="{% url 'main:tryout_delete' tryout.id %}" class="inline-flex bg-red-500 text-white px-4 py-2 rounded-lg shadow-md transition transform
            hover:bg-red-600 hover:-translate-y-1 hover:scale-10">Delete Tryout</a>
            <a href="{% url 'main:show_main' %}" class="inline-flex bg-blue-500 text-white px-4 py-2 rounded-lg shadow-md transition transform
            hover:bg-blue-600 hover:-translate-y-1 hover:scale-10">Back</a>
        </div>
    </div>
</body>
{% include 'footer.html' %}
{% endblock content %}

main/templates/editQuestion/index.html
{% extends 'base.html' %}

{% block meta %}
<title>Edit Question</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}
<div class="flex flex-col gap-4 mt-5 min-h-screen">
    <div class="container mx-auto px-4 py-4 mt-4 max-w-lg bg-white rounded-lg">
        <h1 class="mt-6 text-center text-4xl font-extrabold text-gray-800 mb-8">Edit Question</h1>
        <form method="POST" class="space-y-6">
            {% csrf_token %}
            {% for field in form %}
            <div class="flex flex-col">
                <label for="{{ field.id_for_label }}" class="mb-2 font-semibold text-gray-800 text-2xl">
                    {{ field.label }}
                </label>
                <div class="w-full text-2xl rounded-lg">
                    {{ field }}
                </div>
                {% if field.help_text %}
                <p class="mt-1 text-sm text-gray-100">{{ field.help_text }}</p>
                {% endif %}
                {% for error in field.errors %}
                <p class="mt-1 text-sm text-blue-600">{{ error }}</p>
                {% endfor %}
            </div>
            {% endfor %}
            <div class="flex justify-center mt-6 pb-2">
                <button type="submit"
                    class="group relative w-full bg-[#0b79f7] hover:bg-opacity-100 hover:text-white bg-opacity-10 text-[#0b79f7] border border-[#0b79f7] font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out transform flex-row space-x-2 flex items-center justify-center">
                    Add
                </button>
                <a href="{% url 'main:tryout_detail' tryout.id %}"
                    class="group relative w-full bg-red-500 hover:bg-opacity-100 hover:text-white bg-opacity-10 text-[#0b79f7] border border-[#0b79f7] font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out transform flex-row space-x-2 flex items-center justify-center">
                    Cancel
                </a>
            </div>
        </form>
    </div>
    <style>
        textarea {
            width: 100%;
            height: 150px;
            padding: 12px 20px;
            box-sizing: border-box;
            border: 2px solid #ccc;
            border-radius: 4px;
            background-color: #f8f8f8;
            font-size: 16px;
            resize: none;
        }        
    </style>
</div>
{% include 'footer.html' %}
{% endblock %}

main/templates/editTryout/index.html
{% extends 'base.html' %}

{% block meta %}
<title>Add Tryout</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}
<div class="flex flex-col gap-4 mt-5 min-h-screen">
    <div class="container mx-auto px-4 py-4 mt-4 max-w-lg bg-white rounded-lg">
        <h1 class="mt-6 text-center text-5xl font-extrabold text-gray-800 mb-8">Edit Tryout</h1>
        <form method="POST" class="space-y-6">
            {% csrf_token %}
            {% for field in form %}
            <div class="flex flex-col">
                <label for="{{ field.id_for_label }}" class="mb-2 font-semibold text-gray-800 text-2xl">
                    {{ field.label }}
                </label>
                <div class="w-full text-2xl rounded-lg">
                    {{ field }}
                </div>
                {% if field.help_text %}
                <p class="mt-1 text-sm text-gray-100">{{ field.help_text }}</p>
                {% endif %}
                {% for error in field.errors %}
                <p class="mt-1 text-sm text-blue-600">{{ error }}</p>
                {% endfor %}
            </div>
            {% endfor %}
            <div class="flex justify-center mt-6 pb-2">
                <button type="submit"
                    class="group relative w-full bg-[#0b79f7] hover:bg-opacity-100 hover:text-white bg-opacity-10 text-[#0b79f7] border border-[#0b79f7] font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out transform flex-row space-x-2 flex items-center justify-center">
                    Save Changes
                </button>
                <a href="{% url 'main:tryout_detail' tryout.id %}"
                    class="group relative w-full bg-red-500 hover:bg-opacity-100 hover:text-white bg-opacity-10 text-[#0b79f7] border border-[#0b79f7] font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out transform flex-row space-x-2 flex items-center justify-center">
                    Cancel
                </a>
            </div>
        </form>
    </div>
</div>
{% include 'footer.html' %}
{% endblock %}

main/templates/mainPage/index.html
{% extends 'base.html' %}

{% block meta %}
<title>Tryout-in</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}
<div class="relative m-10 min-h-screen">
    <form method="GET" class="bg-white p-4 rounded-lg shadow-md max-w-4xl mx-auto">
        <div class="grid grid-cols-1 md:grid-cols-4 gap-4 items-center">
            {% for field in filter.form %}
            <div class="flex flex-col">
                <label for="{{field.id_for_label}}" class="text-lg font-semibold text-gray-700 mb-1">
                    {{field.label}}
                </label>
                {{field}}
            </div>
            {% endfor %}
            <div class="flex flex-row gap-4">
                <button type="submit" class="mt-5 px-4 py-3 bg-blue-700 text-white rounded-lg hover:bg-blue-800 shadow-md transition transform hover:-translate-y-1 hover:scale-10 flex items-center justify-center text-center">
                    Search
                </button>
                <button type="button" onclick="resetFilters()" class="mt-5 px-4 py-3 bg-blue-700 text-white rounded-lg hover:bg-blue-800 shadow-md transition transform hover:-translate-y-1 hover:scale-10 flex items-center justify-center text-center">
                    Reset
                </button>
            </div>
        </div>
    </form>
    <a href="{% url 'main:create_tryout' %}" class="mt-5 inline-flex items-center px-4 py-3 text-lg font-medium text-center text-white bg-blue-700 rounded-lg shadow-md transition transform hover:-translate-y-1 hover:scale-10 justify-center">
        Add New Tryout
    </a>
    <div class="flex flex-col gap-4 mt-5 min-h-screen">
        {% for tryout in list_tryout %}
        <div class="w-full p-6 bg-white border border-gray-200 rounded-lg dark:bg-gray-200 dark:border-gray-700 shadow-md transition transform hover:-translate-y-1 hover:scale-100 justify-center">
            <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-black">{{ tryout.title }}</h5>
            <p class="mb-3 font-normal text-gray-700 dark:text-gray-600">Category : {{tryout.category}} </p>
            <span class="mb-4 pb-10 font-normal text-gray-500">Created : {{ tryout.created_at }}</span>
            <div class="flex flex-row gap-3 mt-3">
                <a href="{% url 'main:tryout_detail' tryout.id %}" class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg shadow-md transition transform hover:-translate-y-1 hover:scale-10 justify-center">
                    Quiz Details
                </a>
                <a href="{% url 'main:attempt_quiz' tryout.id %}" class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-green-700 rounded-lg shadow-md transition transform hover:-translate-y-1 hover:scale-10 justify-center">
                    Attempt Quiz
                </a>
            </div>
        </div>
        {% empty %}
            <p class="text-center text-gray-800 mt-4">No Tryouts available</p>
        {% endfor %}
    </div>
</div>
<script>
    function resetFilters() {
        document.querySelectorAll("input, select").forEach(field => {field.value = ""});
        document.querySelector("form").submit();
    }
</script>    
{% include 'footer.html' %}
{% endblock content %}

main/templates/quizResult/index.html
{% extends 'base.html' %}

{% block meta %}
<title>Quiz Result</title>
{% endblock meta %}

{% block content %}
{% include "navbar.html" %}
<div class="flex flex-col min-h-screen">
    <div class="flex flex-col items-center m-5 gap-2">
        <h2 class="text-4xl font-bold text-gray-800 mb-2">Quiz Result</h2>
        <p class="text-lg text-gray-600 mb-4">Score: {{ score }} / {{ total_question }}</p>
    </div>
    
    <div class="flex flex-col m-5 pt-3 pb-5 space-y-4 min-h-svh">
        <h3 class="text-xl font-semibold text-gray-700 mb-3 pb-3">Your Answers:</h3>
        {% for qid, answer in user_answers.items %}
            <div class="flex flex-col bg-gray-50 p-4 rounded-lg shadow gap-3">
                <p class="text-2xl text-gray-800 font-medium">{{ answer.question }}</p> 
                <p> 
                    - Your Answer: <b>{{ answer.user_answer }} {% if answer.is_correct %} (Correct) ✅ {% else %} (Wrong) ❌ {% endif %} </b>
                </p>
                {% if answer.is_correct == False %}
                <p> - Correct Answer: <b>{{ answer.correct_answer }}</b> </p>
                {% endif %}
            </div>
        {% endfor %}
        <a href="{% url 'main:show_main' %}" class="mt-5 max-w-32 bg-blue-500  text-white px-4 py-2 rounded-lg shadow-md transition transform
        hover:bg-blue-600 hover:-translate-y-1 hover:scale-10" >Back to Main</a>
    </div>
</div>
{% include "footer.html" %}
{% endblock content %}

templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		{% block meta %} {% endblock meta %}
		{% tailwind_css %}
		<script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>

		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/dist/tabler-icons.min.css" />
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" crossorigin="anonymous" referrerpolicy="no-referrer" />

		<link rel="preload" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" as="style" crossorigin="anonymous" referrerpolicy="no-referrer" />
		<link rel="preload" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/dist/tabler-icons.min.css" as="style" />
	</head>
	<body>
		<div class="relative overflow-x-hidden min-h-screen bg-blue-100">{% block content %} {% endblock content %}</div>
	</body>
</html>

templates/footer.html
<footer class="fixed bottom-0 left-0 z-20 w-full p-6 pt-6 bg-white border-t border-gray-200 shadow-sm flex flex-col md:flex-row items-center justify-center md:p-6 dark:bg-gray-800 dark:border-gray-600">
    <span class="text-sm text-gray-500 dark:text-gray-400 text-center">
        © 2025 Arshqiii. All Rights Reserved.
    </span>
</footer>

templates/navbar.html
<nav class="w-full bg-white border-gray-200 dark:bg-gray-900 rounded-xs">
<div class=" text-center p-5">
    <span class="self-center font-extrabold text-2xl whitespace-nowrap dark:text-white">TRYOUT PLATFORM</span>
</div>
</nav>

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>